version: '3'

services:
  web:
      build: .
      command: >
        sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
      ports:
        - 8000:8000
      volumes:
        - ./app:/app
      env_file:
        - .env
      depends_on:
        - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
